### PR TITLE
Feature/#933 add brakeman and bundler audit

### LINKED ISSUE #933: Install Brakeman gem
### Descriptive summary

Include a concise description of the issue and any relevant tracebacks if you're reporting a bug.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

### PR DESCRIPTION
**Pull request by bsp3ars**
Fixes #933 #934

Add the brakeman and bundler-audit gems. Also updated the readme with the commands necessary to run them.

### CODE REVIEW

**Comment by hortongn** [comment]
@bsp3ars What's the reason for pinning brakeman to v5.1.1?

**Comment by bsp3ars** [comment]
@hortongn I pinned it at v5.1.1 because I thought you needed to give a ref for github repos in the Gemfile

**Comment by hortongn** [comment]
@bsp3ars Just change it to `gem 'brakeman'` and that it should be fine.  It's a published gem and we don't need to point to it's GitHub repo.

**Review by hortongn — APPROVED** [review]
Looks good to me.  @scherztc?

**Pull request merged**
