### PR TITLE
Port over Scholar's permalinks feature

### LINKED ISSUE #207: Port over Scholar's permalinks feature
### Descriptive summary

Scholar displays a link to the current page at the bottom of all collection, work, and file show pages.

On work and file pages the format is
`Permanent link to this page: https://scholar.uc.edu/show/4x51hj32t`

On collection pages the format is
`Link to this page: https://scholar.uc.edu/collections/fj236221c`

Note: we have already added the `/show/` route to UCrate (see https://github.com/uclibs/ucrate/commit/9fa8f362781e7f10e2f47fa132bc0ec11cfcd6f5).  We just don't put the link at the bottom of the pages yet.

Commit in Scholar: https://github.com/uclibs/scholar_uc/commit/b53d158e4e87466927d644366b2c5b5b6d4f7649

### PR DESCRIPTION
**Pull request by changy66**
Fixes #207 

- Added permalinks_presenter in 'collections_controller.rb', 'profiles_controller.rb', 'file_sets_controller.rb', and work types controller
- Ported partial permalink. 
- Added partial to 'layouts/hyrax.html.erb'
- Added link in feature spec of type works, collections and user profile.

### CODE REVIEW

**Comment by crowesn** [comment]
@changy66 Please add feature specs to verify URL is displaying in all appropriate views.

**Comment by changy66** [comment]
Right! I am still working on it, I will add spec tomorrow :)

On May 31, 2018, at 3:04 PM, Sean Crowe <notifications@github.com<mailto:notifications@github.com>> wrote:


@changy66<https://github.com/changy66> Please add feature specs to verify URL is displaying in all appropriate views.

**Comment by crowesn** [comment]
@changy66 I think this needs just a quick rebase and it should be ready to go.

**Comment by crowesn** [comment]
@changy66 There are some rubocop failures.

**Comment by crowesn** [comment]
@changy66 One more quick rebase and we should be ready to go.

**Pull request merged**
