### PR TITLE
setup rubocop for ucrate and fix any pre existing issues

### LINKED ISSUE #10: Set up Rubocop
Depends on #1

### PR DESCRIPTION
**Pull request by lawhorkl**
closes #10

### CODE REVIEW

**Comment by lawhorkl** [comment]
just a note if we can't add to travis running `bundle exec rubocop` needs to be done before submitting any PR and should be a part of reviewing any PR on a regular basis to be effective

**Comment by hortongn** [comment]
@lawhorkl When I ran rubocop locally I got a lot of warnings like this:

`Warning: unrecognized cop RSpec/NamedSubject found in /home/vagrant/Development/ucrate/ucrate/.rubocop_todo.yml`

Those were showing up because the `rubocop-rspec` gem wasn't loading for some reason.  Once I changed the Gemfile to `gem 'rubocop-rspec', '~> 1.5'` and ran rubocop again the warnings went away and it found 8 offenses in spec files.

So we adjust the Gemfile to get the rspec piece running properly and fix those offenses before merging this.

**Comment by hortongn** [comment]
Also, we should change the `TargetRubyVersion` to ruby 2.3

**Comment by lawhorkl** [comment]
@hortongn i pinned the gem in my Gemfile and still got those warnings

**Comment by lawhorkl** [comment]
however I updated the ruby version and found some more style issues il be sure to go through and correct what I missed

**Comment by hortongn** [comment]
Kyle, I altered my Gemfile to match the Sufia.gemspec:

`gem 'rubocop', '~> 0.42.0'`
`gem 'rubocop-rspec', '~> 1.5'`

Then after running rubocop again I got the following offenses for spec files:

spec/controllers/workgroups_controller_spec.rb:61:5: C: RSpec/HookArgument: Omit the default :each argument for RSpec hooks.
    before(:each) { sign_in user }
    ^^^^^^^^^^^^^
spec/features/end_to_end_spec.rb:4:3: C: RSpec/ExampleLength: Example has too many lines. [31/7]
  scenario "workflow" do ...
  ^^^^^^^^^^^^^^^^^^^^^^
spec/requests/workgroups_spec.rb:3:1: C: RSpec/EmptyExampleGroup: Empty example group detected.
RSpec.describe "Workgroups", type: :request do
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/routing/workgroups_routing_spec.rb:3:1: C: RSpec/EmptyExampleGroup: Empty example group detected.
RSpec.describe WorkgroupsController, type: :routing do
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/routing/workgroups_routing_spec.rb:4:3: C: RSpec/EmptyExampleGroup: Empty example group detected.
  describe "routing" do
  ^^^^^^^^^^^^^^^^^^
spec/views/workgroups/index.html.erb_spec.rb:4:3: C: RSpec/HookArgument: Omit the default :each argument for RSpec hooks.
  before(:each) do
  ^^^^^^^^^^^^^
spec/views/workgroups/new.html.erb_spec.rb:4:3: C: RSpec/HookArgument: Omit the default :each argument for RSpec hooks.
  before(:each) do
  ^^^^^^^^^^^^^
spec/views/workgroups/show.html.erb_spec.rb:4:3: C: RSpec/HookArgument: Omit the default :each argument for RSpec hooks.
  before(:each) do
  ^^^^^^^^^^^^^

**Pull request closed without merging**
