### PR TITLE
Upgrade to ruby2.7 and bundle update, hyrax 2.9.4

### LINKED ISSUE #883: Update to ruby 2.6.x or 2.7.x, Hyrax to 2.9.x
### Descriptive summary

ruby 2.5 has an EOL of March 31, 2021.  Before the end of 2020 we should update Scholar to work with ruby 2.6 or 2.7.

Using ruby 2.7 would require us to upgrade to at least Hyrax 2.8.0.  Earlier versions of Hyrax do not support ruby 2.7.

### LINKED ISSUE #897: Bundle update
Probably best to first upgrade ruby (#883) before updating gems

Time to update gems.

Be sure to resolve any dependency alerts listed at
https://github.com/uclibs/ucrate/network/alerts

Add the list of updated gems to the commit message.

### PR DESCRIPTION
**Pull request by crowesn**
Fixes #897 
Fixes #883 
Related #882 

Upgrade to ruby 2.7.2, upgrade to hyrax 2.9.4, bundle update.

### CODE REVIEW

**Comment by crowesn** [comment]
I think this is ready to go - the ci-2.5.3 is hanging out but I think it's a just an artifact.

**Comment by crowesn** [comment]
- [ ] Compare files for overrides
- [ ] Review front-end new features
- [ ] Manual test script

**Comment by scherztc** [comment]
We should probably be pushing for the 2.9 version of Hyrax if we are going to do this upgrade.

See : Slack channel comment 'here are several security patches the 2.9 line, so if there's anything we can do on the Hyrax side help you move forward, i'd want to find that out'

**Comment by crowesn** [comment]
Upgrade hyrax to [2.9.3](https://github.com/samvera/hyrax/tree/v2.9.3)

**Comment by crowesn** [comment]
@uclibs/adu-developers This is complaining about test coverage but I think it's ready for review.

**Comment by scherztc** [comment]
@crowesn :  This passed all of my test locally and feels good on my code read through.  It looks like most of the changes really are rubocop and helper oriented.  Can you tell me if there is anything in the hyrax change log that I should specifically click test? (2.6 -> 2.9)

**Comment by scherztc** [comment]
@crowesn :  Here is my take away from the Changelog for Hyrax:

Deprecated the collection size calculation behavior.
Fixed nested memberships
Adding of Children Works
Improve IIIF peformance
Remote Identifiers
Fix File Versioning

I will do some click testing around these areas.

**Comment by crowesn** [comment]
Update ruby versions for capistrano.

**Comment by scherztc** [comment]
Steps of things we are going to have to do to the server environment after merging:

Update ruby to version 2.7.2
        download the ruby .tar.gz from https://www.ruby-lang.org/en/downloads/
	uncompress the tarball
	cd into the uncompressed directory
	./configure --prefix=/usr
	make
	sudo make install
	test the proper version is in place with ruby -v

**Pull request merged**
