### PR TITLE
add title and description to workgroups and update specs

### LINKED ISSUE #7: Add title and description to workgroups
Expose the date and time the workgroup was created

User story: https://trello.com/c/60L1VDHS/28-basic-workgroup-metadata

Depends on #3

### PR DESCRIPTION
**Pull request by lawhorkl**
closes #7

### CODE REVIEW

**Comment by hortongn** [comment]
I think we need to fix the way the migration is handled.  You're adding two columns to an existing migration instead of creating a new one.  I can show you the problem I'm having tomorrow.

**Comment by hortongn** [comment]
The title and description migration is working for me after your change.  

One more issue: you have a "destroy" link in your workgroup index view, but there's no destroy action action in the controller.  So the link fails.  Just remove the destroy link from the view.  Deleting a workgroup is beyond the scope of this issue anyway.  After that I think we're good to merge.

**Comment by lawhorkl** [comment]
Hm... That's odd, I must have not caught it when I copied the generated views.

**Comment by lawhorkl** [comment]
@hortongn removed the line!

**Pull request merged**
