### PR TITLE
Updates Hyrax to version 2.6.0 and BrowseEverything to version 1.0.0

### LINKED ISSUE #603: Get Dropbox working properly with Browse Everything
### Descriptive summary

Make the needed changes to get Dropbox working for cloud uploads.

### LINKED ISSUE #604: Get Google Drive working properly with Browse Everything
### Descriptive summary

Make the needed fixes to get Google Drive working for cloud uploads

See https://github.com/uclibs/ucrate/issues/417 and https://github.com/uclibs/scholar_uc/issues/1379

### PR DESCRIPTION
**Pull request by scherztc**
Fixes #603, Fixes #604 

Present short summary (50 characters or less)

With the upgrade of the Hyrax gem to version 2.6.0 we get full BrowseEverything 1.0 support. 
With BrowseEverything 1.0, we get full support for Box, DropBox, S3, and Google Drive support.
We also added environmental variables to our browse_everything.yml file and set their definition in the env files.

You can test this PR locally with the API credentials up on git.uc.edu.

### CODE REVIEW

**Comment by hortongn** [comment]
@scherztc Are there really no other overrides or specs that need updating?  There were over 450 commits on Hyrax from v2.5.1 in May to v2.6.0 in November.

**Comment by hortongn** [comment]
@scherztc Remember to find out what other overrides, etc. we may have to tweak.  You should be able to do a github compare of v2.5.1 and v2.6.0 to see all the files changed.

**Comment by scherztc** [comment]
@hortongn It looks like there are only 30 commits between v.2.5.1 and v2.6.0.  I will examine the commits and see what might be an over-ride or need testing.  

https://github.com/samvera/hyrax/compare/v2.5.1...v2.6.0

**Comment by scherztc** [comment]
There are commits around setting up CircleCi and get to the latest ruby version.

The next set of commits are around the BrowseEverything environment and I have accounted for those in the PR.

Then it is work on the Actor Stack that I will check : https://github.com/samvera/hyrax/commit/4f363c75345e21ff14d59422e2d5248fda0e8d4e

Bug Fix to Original File Set Indexer : https://github.com/samvera/hyrax/commit/17b4ac082d04845d1963a8d81bf3273627269e13

Documentation Updates

Update Hydra_Editor and Check Workflow : https://github.com/samvera/hyrax/commit/9407a6f6cede0bf9f3edf7e32fc1ae0c1f4d618a

**Comment by scherztc** [comment]
@hortongn : I examined all of the 30 commits and didn't find any overwrites that needed to be tested or extended.  Please start the review process of this PR.

**Comment by hortongn** [comment]
@scherztc The issues I saw with Google Drive:

Sign in - Google Accounts

Action Controller  Exception caught

**Comment by scherztc** [comment]
@hortongn :  After looking at our Google Drive Applications in the google console (https://console.developers.google.com/) neither of our environments (DEV/PROD/QA) are VERIFIED.  I submitted the DEV/PROD applications for verification.  They are under review:

Your consent screen is being verified. This may take up to several weeks. Your last approved consent screen is still in use.

I will monitor it by email.

**Comment by scherztc** [comment]
@hortongn :  I think we should still merge the code and comment out the Google Drive in the browse_everything.yml.  Let me know if you are okay with this direction and I will continue with the deploy checklist.

**Pull request merged**
