### PR TITLE
Sets solr version to 8.11.1 and fedora version to 4.7.5

### PR DESCRIPTION
**Pull request by scherztc**
Sets solr_wrapper and fcrepo_wrapper to versions.
Removes StandardFilterFactory from solr config.
Sets solr and fcrepo version in .circleci config.

### CODE REVIEW

**Review by hortongn — COMMENTED** [review]
Will merge this after we confirm these versions work in our server environments

**Comment by scherztc** [comment]
Coverage report generated for RSpec to /Users/scherztc/ucrate/coverage. 3203 / 3376 LOC (94.88%) covered.

**Review by hortongn — COMMENTED** [review]
@scherztc Everything in the PR looks good except the .xml files have a TON of changes to them.  Makes me nervous.  Did you get these XML files from a non-Hyrax app?  I thought we were making minimal changes to the XML files to make solr happy.

**Comment by scherztc** [comment]
> @scherztc Everything in the PR looks good except the .xml files have a TON of changes to them. Makes me nervous. Did you get these XML files from a non-Hyrax app? I thought we were making minimal changes to the XML files to make solr happy.

@hortongn :  Here are all of the changes that I wanted to implement.  This is coming from Duke University per my conversations with them in Tech Meetings.  :  https://github.com/UNC-Libraries/hy-c/pull/764/files#diff-2491cd062e834e7f6a211731cf661df648bec3742e3c3f9065c58a92813e884c.  I slimmed it down to just the two .xml files.  

I also wanted to log into ScholarQA one more time to see what files I am using on there.  

In the end, I think the SOLR changes we made way back here, would meet the minimal requirements.  So we could pull of these files out of the upgrade like the rest of the Duke stuff?

**Pull request merged**
