### PR TITLE
Adds support for Google Analytics.

### LINKED ISSUE #413: Implement statistics changes from Scholar
### Descriptive summary

We made several tweaks to scholar_uc to get statistics working for us.  So we need to...
1. Figure out what tweaks are still needed when using Hyrax 2.x
1. Implement those tweaks

The latest changes in scholar_uc to implement this can be seen here:
https://github.com/uclibs/scholar_uc/compare/1c59a0a3f57837308d1c755936691e0e52441594...0618cf55d046d869e73533ab4f70c8c306786bcd

A good first step is to bring over all those changes and get the specs passing.  We will then need to try testing it on scholar-qa.uc.edu

### PR DESCRIPTION
**Pull request by scherztc**
Fixes #413 

Present short summary (50 characters or less)

This PR sets the variables needed for connecting to Google Analytics to provide view and download stats for each work and file_set.  It also has the machinery for updating the totals in the dashboard.

The updating machinery includes rake task, database migrations, and copy scripts.

Refer to the notes on Legato for using in non-production environments :
https://github.com/samvera/hyrax/wiki/Analytics-workaround-for-non-production-environments

Refer to config_vault for authentication file and google API connection information:
https://git.uc.edu/UCLIBS/config_vault

### CODE REVIEW

**Comment by scherztc** [comment]
uclibs/scholar_uc@1c59a0a...0618cf5

**Comment by scherztc** [comment]
I ran both of the rake commands locally without error.

RAILS_ENV=production bundle exec rake custom_stats:update_index
RAILS_ENV=production bundle exec rake custom_stats:collect LIMIT="1000" DELAY="2" RETRIES="8"

**Comment by scherztc** [comment]
screen shot 2018-11-29 at 3 54 41 pm


I like this locally.

**Comment by scherztc** [comment]
I am slightly concerned by the 0 views on the file sets. I don't think this is a problem with the tally.  I am getting 0 views on my test file locally in GA.  This could be just a timing thing, but may be a problem.

**Comment by hortongn** [comment]
@scherztc One needed change I'm seeing so far is you need to set the analytic_state_date in config/initializers/hyrax.rb to be the same date we are using in scholar_uc. 
 You need to match this https://github.com/uclibs/scholar_uc/blob/develop/config/initializers/hyrax.rb.bamboo#L47

**Comment by hortongn** [comment]
@scherztc I haven't finished reviewing the whole PR, but I'm sending you issues as I find them so you can start to address them.  Your PR doesn't include a "Work Views" count on the user's profile page.  I think you are missing the changes we made to scholar_uc here:
https://github.com/uclibs/scholar_uc/pull/1905

**Pull request merged**
