### PR TITLE
REST API

### LINKED ISSUE #750: Implement a REST API interface that allows work creation
### Descriptive summary

Refs: #707

We need a (versioned) API for integration with Research Directory and other services.  The API should allow us to send JSON to Scholar to create and update works.

The API should allow remote services to use an API key to create content (instead of passing user authentication)

### Resources:
* Original issue on scholar_uc_legacy: https://github.com/uclibs/scholar_uc_legacy/issues/19
* API Documentation : https://systest.ahctest.uc.edu/eprof/cfc/fetcheprofdatadoc.cfc?method=getdocumentation
* Example of API return on a 6+2 query: https://git.uc.edu/UCLIBS/api-documentation/blob/master/research_directory/get_wb_page_data-sample-formatted.xml

### Sample JSON responses for Scholar searches, collections, works, and files:
* https://scholar.uc.edu/catalog.json
* https://scholar.uc.edu/collections/h128nf812.json
* https://scholar.uc.edu/concern/images/kw52j9012.json
* https://scholar.uc.edu/concern/parent/kw52j9012/file_sets/cn69m5141.json

### Other Samvera implementations using APIs for ingest
* https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+Ingest+API
* https://github.com/aic-collections/aicdams-lakeshore/blob/master/script/ingest-api.sh

### Minimal set of components for ingesting a file into Scholar
* UC login (and an established user object in Rails database)
* Select a work type
* Metadata
    * Title
    * Creator (multiple)
    * College
    * Program/Department
    * Description
    * License
    * Advisor (multiple) - Student Works, ETDs
    * Degree Program - ETDs
* Select visibility
* Read and agree to distribution license
* Upload file

### Tasks
- [x] Collections: create, update, read
- [x] Works: create, update, read
- [x] Users: create, update, read
- [x] File upload, attach, characterize
- [x] API keys
- [x] Validation
- [x] API versioning
- [x] Documentation
- [x] Testing file upload in bulk

### PR DESCRIPTION
**Pull request by bsp3ars**
Fixes #750

Implements a REST API using a gem called grape. All current documentation is in:
* https://github.com/uclibs/ucrate/wiki/API
* https://github.com/uclibs/ucrate/wiki/API---Using-Postman
* https://github.com/uclibs/ucrate/wiki/API---Works
* https://github.com/uclibs/ucrate/wiki/API-Collections

### CODE REVIEW

**Comment by bsp3ars** [comment]
Currently the temp/api-deploy branch is on curly, which has this and the capistrano deploy combined so that it can be easily deployed. We used the API to upload a 10GB file to http://curly.libraries.uc.edu:3002/concern/generic_works/1c18df763. After checking the md5's of my original copy and the uploaded version, they are identical.

**Comment by bsp3ars** [comment]
@hortongn I made the changes requested. As soon as Travis finishes we should be good to go

**Comment by bsp3ars** [comment]
@hortongn My apologies, I misunderstood that the field was mandatory. It should be good now.

**Comment by hortongn** [comment]
A chunk of the API's users.rb file isn't covered by tests:
https://coveralls.io/builds/26783021/source?filename=app/api/scholar/v1/users.rb

**Comment by bsp3ars** [comment]
@hortongn The change fixed the test and the coveralls

**Pull request merged**
