### PR TITLE
[WIP] Port over license wizard from Scholar 3

### LINKED ISSUE #235: Port over license wizard from Scholar 3.
### Descriptive summary

Port over license wizard from Scholar 3.

### Related work

https://github.com/uclibs/scholar_uc/pull/981/files
https://github.com/uclibs/scholar_uc/pull/1200/files

### PR DESCRIPTION
**Pull request by changy66**
Fixes #235 

Copied files from Scholar
Added 'license' to primary_terms in works types controller to set 'license' required.
Added selecting 'license' in create works types feature test.

### CODE REVIEW

**Comment by scherztc** [comment]
We need to display both the license and rights fields on the work show page.

screen shot 2018-07-03 at 11 26 23 am

**Comment by changy66** [comment]
I am still looking for the license partial. I will get back to you if I am blocked.

On Jul 11, 2018, at 2:13 PM, thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


@scherztc requested changes on this pull request.

@changy66<https://github.com/changy66> : Any luck getting license to display on the show page?

**Comment by scherztc** [comment]
@changy66 :  Rebase on Develop and let's see if LICENSE shows on the work show view, now.

**Comment by scherztc** [comment]
Re-opening PR with new branch.

**Pull request closed without merging**
