### PR TITLE
Added bixby gem with bundle update

### LINKED ISSUE #166: Try Bixby and research if we should go with it
### Descriptive summary

[Bixby](https://github.com/samvera-labs/bixby) gem has RuboCop Defaults for Samvera Community projects. Try it for UCrate and see if it is worth using the gem.

### PR DESCRIPTION
**Pull request by jayanthdeejay**
Fixes #166

Present short summary (50 characters or less)

* Added Bixby gem and had to run bundle update after. 
* Also ran
```ruby
rubocop --auto-correct
```
* Cleaned up .rubocop.yml file.
* Got rid of cops, already included in bixby.

### CODE REVIEW

**Comment by jayanthdeejay** [comment]
All failed tests except one is known and depend on the [PR](https://github.com/uclibs/ucrate/pull/214). Once that is merged, I'll rebase this branch and will rerun all the checks.

**Comment by hortongn** [comment]
I'm concerned this may conflict with the change to `TargetRubyVersion` in Sean's PR #204 (https://github.com/uclibs/ucrate/pull/204/files#diff-11a0d7906801d9dea0eccb85667ad811).

So let's hold on this until that PR is merged and then see what we need to do to accommodate the change to `TargetRubyVersion`

**Comment by crowesn** [comment]
@hortongn I did a rebase on this - okay for me to still review or should someone else take it?

**Comment by crowesn** [comment]
@uclibs/developers I made some changes to this to accommodate PR #204 
Someone else please review.

**Pull request merged**
